export const UPDATE_TEXT = 'UPDATE_TEXT'
export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_EDIT_TODO = 'TOGGLE_EDIT_TODO'
export const STOP_EDIT_TODO = 'STOP_EDIT_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
